- Dockerfile
> chore(docker): use ENTRYPOINT instead of CMD in docker

- ui/src/Components/Grid/AlertGrid/index.js
- ui/src/Components/Grid/AlertGrid/index.test.js
This reverts commit d896fa72b2dd442c7615a63e6b9c934de310aab9.
This causes issues with grid rendering - when alert is removed space it was using is not reclaimed.
> Revert "chore(ui): avoid full grid repack on new alerts"

- internal/config/config.go
> fix(config): use correct variable name for --config.file

- ui/src/Components/Grid/AlertGrid/index.js
This reverts commit bc720412226e748dbcf43c877d358bd67b71d58c.
Breaks alert action menu, it gets hidden under next alert group div.
> Revert "chore(ui): use transform positioning for grid elements"

- ui/src/Components/Grid/AlertGrid/index.js
This is a short term fix to reduce potential re-ordering of alert groups on the grid. This needs to be controlled by user.
> fix(ui): sort alert groups by id before slicing

- ui/src/Components/FetchPauser/index.js
- ui/src/Components/FetchPauser/index.test.js
- ui/src/Components/Fetcher/index.js
- ui/src/Components/Fetcher/index.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.test.js
- ui/src/Components/NavBar/FetchIndicator/__snapshots__/index.test.js.snap
- ui/src/Components/NavBar/FetchIndicator/index.js
- ui/src/Components/NavBar/FetchIndicator/index.test.js
- ui/src/Components/NavBar/index.js
- ui/src/Stores/AlertStore.js
This will prevent whack-a-mole when user clicks on an action menu and then grid re-renders moving it around
> feat(ui): pause fetching when alert/group menu is open

- Makefile
- main.go
This will add raw files from ui/src into the binary and allow fetching those. That way sentry.io can fetch those via source maps references and show more readable exceptions
> feat(sentry): bundle raw UI source files for sentry

- ui/src/Components/NavBar/index.js
- ui/src/Components/NavBar/index.test.js
Don't destroy navbar since modals are mounted on it + update visibility after transition so animations work as expected
> fix(ui): better navbar hiding when idle

- ui/src/ErrorBoundary.js
- ui/src/ErrorBoundary.test.js
As reported via #77 countdown timer might be updated more often than 1s since we don't protect against multiple setInterval() calls, add a check
> fix(ui): don't let multiple exceptions set multiple timers

- .travis.yml
/usr/local/bin/heroku is installed by the script, /usr//bin/heroku might be there installed by travis, ensure we use the correct one
> fix(heroku): use absolute path for heroku command on travis

- ui/src/Components/MultiSelect/index.js
It's currently 1 which is the same as buttons on the calendar picker used in the silence form, dropdown needs to have higher value
> fix(ui): set high z-index on react-select dropdown menu

- ui/src/Components/SilenceModal/SilencePreview/__snapshots__/index.test.js.snap
- ui/src/Components/SilenceModal/SilencePreview/index.js
This will be confusing since we deduplicate receivers, drop the count and more info
> refactor(ui): drop alert count from silence preview

- ui/src/Components/LabelSetList/__snapshots__/index.test.js.snap
- ui/src/Components/LabelSetList/index.js
- ui/src/Components/SilenceModal/SilencePreview/__snapshots__/index.test.js.snap
The way list-group-flush is styled any extra element on the ul level seems to be causing top/bottom borders to show up, move it under a dedicated div to prevent that from happening, with list-group-flush we want borders only between label set elements
> fix(ui): move ul to a dedicated div to prevent bottom border

- Gopkg.lock
- Gopkg.toml
A version was tagged, pin it instead of tracking master branch
> chore(deps): pin raven-go to latest version

- ui/src/Common/Colors.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/__snapshots__/index.test.js.snap
- ui/src/Components/LabelSetList/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/BaseLabel/index.js
- ui/src/Components/Labels/BaseLabel/index.test.js
- ui/src/Components/Labels/FilterInputLabel/index.js
- ui/src/Components/Labels/FilteringCounterBadge/index.js
- ui/src/Components/Labels/FilteringLabel/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/FilteringLabel/index.js
- ui/src/Components/Labels/HistoryLabel/index.js
- ui/src/Components/Labels/StaticLabel/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/StaticLabel/index.js
- ui/src/Components/SilenceModal/SilencePreview/__snapshots__/index.test.js.snap
Merge into a single function since both className & style are tied together and as such are better of if selected using a single logic. Fixes some minor UI glitches like ellipsis color on truncated labels with custom color
> refactor(ui): cleanup label color/style selection

- .travis.yml
Move all lint jobs to a stage named 'Lint' and test jobs to a stage named 'Test', this will allow Travis to run all jobs in the same stage in parallel, speeding up CI tasks
> chore(ci): parallelize Travis CI jobs by using same name for stages

- .travis.yml
sudo is being deprecated
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> chore(ci): remove sudo options from Travis config

- .travis.yml
- renovate.json
go modules leave checksums of old releases which gets removed when tidy is run, so the diff check is likely to pick us something every time a go module was bumped. Can't have it on CI this way as it will keep failing jobs
> fix(ci): drop go module tidy check from travis

- Makefile
- assets.go
- assets_test.go
This was disabled because bindata_assetfs.go file was stored in git, not it's not so we can re-enable it and get accurate Last-Modified headers in HTTP responses
> chore(build): store file metadata when generating binary assets

- .gitignore
- docs/CONFIGURATION.md
- docs/example.yaml
- internal/alertmanager/models.go
- internal/alertmanager/upstream.go
- internal/config/config.go
- internal/config/config_test.go
- internal/config/models.go
- internal/uri/file.go
- internal/uri/http.go
- internal/uri/uri.go
- internal/uri/uri_test.go
- main.go
Allows custom HTTP headers to be set via a configuration file (does not provide a method for setting on the command line). This should apply the headers to every request submitted to a specific AlertManager.
> add support for custom HTTP headers

- .travis.yml
It's triggered only on merges right now, needs to also happen on tag
> fix(deploy): trigger docker deploy on new tag

- assets.go
Since those files can change at any time we should ensure that they are not cached
> fix(backend): don't cache custom assets

- demo/Dockerfile
`>= 0.16` doesn't yet work due to #115
> chore(demo): pin alertmanager to 0.15.3 on demo site

- proxy.go
When constructing proxy path to listen on for requests to pass upstream check if listen.prefix ends with / and if no inject it.
Fixes #386
> fix(proxy): check for trailing slash on listen.prefix when proxy is on

- .travis.yml
Docker is used to build the image, no need to set GO111MODULE
> chore(ci): drop Go modules env from heroku job

- .travis.yml
Still not building dockers on new release, looks like 'tag IS present' is the correct syntax for this condition after all
> fix(ci): fix tag condition for travis

- codecov.yml
Those are noisy and most of them are no-op
> chore(ci): disable codecov comments

- docs/CONFIGURATION.md
- internal/alertmanager/models.go
- views.go
It's a fake label so it needs special code to inject the color information to the API response.
Fixes #421
> fix(api): apply colors to the @alertmanager label

- ui/package.json
- ui/src/App.scss
- ui/src/Fonts.scss
- ui/yarn.lock
With this change the browser won't need to make any external requests to render the page.
Fixes #425
> feat(ui): bundle Lato fonts

- ui/src/Fonts.scss
This tells the browser to use a fallback font until Leto is loaded, which speeds up initial rendering, especially on slow clients
> feat(ui): set font-display swap policy

- assets.go
It's currently 30 days, if that works than why not set it to a much higher value
> chore(backend): bump caching headers to 1 year

- .travis.yml
travis_retry allows to retry a command a few times if it fails, use it for all commands that depend on external resources which could fail, so that we reduce noise caused by temporary issues with docker hub or npm/yarn registry
> feat(ci): wrap fragile commands with travis_retry

- ui/src/Components/Grid/AlertGrid/index.js
- ui/src/Components/Grid/AlertGrid/index.test.js
- ui/src/Components/MainModal/Configuration/AlertGroupConfiguration.test.js
- ui/src/Components/MainModal/Configuration/AlertGroupSortConfiguration.js
- ui/src/Components/MainModal/Configuration/AlertGroupSortConfiguration.test.js
- ui/src/Components/MainModal/Configuration/FetchConfiguration.test.js
- ui/src/Components/MainModal/Configuration/SortLabelName.js
- ui/src/Components/MainModal/Configuration/__snapshots__/AlertGroupConfiguration.test.js.snap
- ui/src/Components/MainModal/Configuration/__snapshots__/AlertGroupSortConfiguration.test.js.snap
- ui/src/Components/MainModal/Configuration/__snapshots__/FetchConfiguration.test.js.snap
- ui/src/Components/MainModal/Configuration/index.js
- ui/src/Components/MainModal/Configuration/index.test.js
- ui/src/Components/MainModal/__snapshots__/MainModalContent.test.js.snap
- ui/src/Stores/Settings.js
This adds the ability for user to sort the grid of alerts via selected attribute.
UI configuration is provided to setup if timestamps or labels should be used to sort alerts.
> feat(ui): allow sorting alert grid

- demo/karma.yaml
- docs/CONFIGURATION.md
- internal/config/config.go
- internal/config/config_test.go
- internal/config/models.go
- views.go
Those options are only valid for sorting, so move it to the new config section where all sort options live
> chore(config): move value mapping options to grid:sorting section

- .travis.yml
This is to stop building docker images twice for jobs triggered on merge and release tag
> chore(ci): only test docker builds for pull requests

- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
alertsToRender can be higher than the number of alerts in a group if the number keeps changing. This means we might end up with 'Showing 30/10', so ensuring that we don't show a number higher than the actual group size will make it more accurate
> fix(ui): use current number of alerts in the count label

- Dockerfile
- demo/Dockerfile
Modules no longer require being inside the GOPATH, moving it outside ensures that we don't use anything from GOPATH anymore
> chore(go): use /src as source dir when building Go code

- .travis.yml
Linked issue was resolved as of Go 1.12, so this is no longer needed
> chore(ci): drop go mod download calls

- ui/src/Common/Query.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/BaseLabel/index.js
- ui/src/Components/Labels/FilteringCounterBadge/index.js
- ui/src/Components/Labels/FilteringLabel/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/FilteringLabel/index.js
- ui/src/Components/Labels/FilteringLabel/index.test.js
When user clicks on a label we apply a foo=bar filter, this change allows to add a foo!=bar filter by holding Alt key when clicking.
Fixes #485
> feat(ui): use not-equal operator when user alt+clicks on a label

- renovate.json
This change caused lock file to be generated in a way that generates local changes on build, drop it
> fix(ci): disable yarn & npm lock file deduplication

- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap
This changes handling of annotation hide/show clicks. Right now annotation details are toggled when anything inside the annotation div is clicked. With this change showing annotation details stays the same (click anywhere), but hiding those details only works when clicking the minus icon. A tooltip was added and cursor changes to pointer only when hoovering over clickable elements.
Fixes #518
> chore(ui): hide annotation details only when clicking on the - icon

- ui/src/Components/Animations/DropdownSlide/index.css
- ui/src/Components/Animations/DropdownSlide/index.js
- ui/src/Components/Animations/MountFade/index.js
- ui/src/Components/Animations/MountModal/index.js
Cleanup props by removing 'in' which is passed in from parent and set dropdown max-height to be biggish, so that the dropdown doesn't need to expand more after animation is complete
> fix(ui): tweak animations

- internal/models/api.go
Prevent different order between requests, which can also break random tests
> fix(api): always sort shared silences

- go.mod
- go.sum
- internal/mock/mock.go
- proxy_test.go
- views_test.go
This is to use v1.0.0 that was just released, gopkg.in doesn't work anymore
> chore(backend): switch jarcoal/httpmock imports to use github

- ui/src/Components/Labels/FilterInputLabel/index.js
- ui/src/Components/Labels/FilterInputLabel/index.test.js
Right now counter badge is rendered on every filter instance, but if there's only one filter that counter has the same value as the total alert counter on left side. With this change counter badge will only be rendered if there's a filter with hits != total alert count
> feat(ui): hide filter counter value when not needed

- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
Right now the title and the body blends together in the UI, add background color to make it easier to show where title bar ends and where the alert body starts
> refactor(ui): add background color to the alert group title

- ui/src/Components/Grid/index.js
- ui/src/Components/Grid/index.test.js
Resizing browser window requires reseting the grid, since the number of columns might change. Add event handlers to handle that
> fix(ui): reset grid after browser reset

- ui/package.json
- ui/src/Components/Grid/AlertGrid/index.js
- ui/yarn.lock
When fonts are loaded size of rendered elements might change, which can break the grid display, trigger a repack to fix that
> fix(ui): repack alert grid on font load

- ui/src/Components/Labels/FilterInputLabel/index.css
- ui/src/Components/Labels/FilterInputLabel/index.js
Text is not aligned properly on macOS/chrome and spinner for unapplied filters is moved to the top
> fix(ui): cleanup filter input css classes

- ui/src/Components/Labels/FilterInputLabel/index.js
Tooltip component creates a div element which is currently missing mw-100 (and others) so it can be bigger than the wrapping label span
> fix(ui): ensure that filter input labels are truncated if too long

- assets.go
- main.go
We can't set any headers after c.Abort() was called (which will happen in the static files middleware if file was found) so we need to refactor this code. New logic will be: set all headers early, if file is found response will include those, later add second middleware that clears those headers, it will only be hit if file wasn't found, so we'll clear headers on all 404s
> fix(backend): correctly handle expires for static files

- ui/src/Common/Colors.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.js
- ui/src/Components/Labels/FilteringCounterBadge/index.js
- ui/src/Components/Labels/FilteringCounterBadge/index.test.js
- ui/src/Components/MainModal/Configuration/AlertGroupTitleBarColor.js
- ui/src/Components/MainModal/Configuration/AlertGroupTitleBarColor.test.js
- ui/src/Components/MainModal/Configuration/__snapshots__/AlertGroupTitleBarColor.test.js.snap
- ui/src/Components/MainModal/Configuration/__snapshots__/index.test.js.snap
- ui/src/Components/MainModal/Configuration/index.js
- ui/src/Components/MainModal/__snapshots__/MainModalContent.test.js.snap
- ui/src/Stores/Settings.js
This enables second mode for titlebar styling - enabling it will cause the background to be set to the same color as the alerts, but only if all alerts in a group are in the same state.
> feat(ui): add colored second display style for titlebar

- ui/src/Components/Grid/AlertGrid/index.js
50ms is very noticable and one can see groups overlapping each other, 10ms is nicer
> fix(ui): lower repack debounce

- ui/src/Components/Fetcher/index.js
- ui/src/Components/Fetcher/index.test.js
Right now the very fist fetch() happens right after Fetcher instance is created, which might be while a lot of other components are still being created. Wrap it inside requestAnimationFrame so it's executed once the browser is (fairly) idle
> fix(ui): delay initial fetch until browser is idle

- ui/src/Components/Grid/AlertGrid/index.js
- ui/src/Components/Grid/AlertGrid/index.test.js
Sorting by timestaps should be reversed - most recent timestamps first
> fix(ui): fix fallback sorting by timestamps

- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.js
Because every alert group uses 'position: absolute' our menu content rendered after clicking on group header or each alert dropdown is hidden under neighbour groups. To fix this we'll add 'z-index: 100' to the group with currently open menu.
> fix(ui): fix alert menu content being under other alert groups

- ui/src/Components/MainModal/index.js
- ui/src/Components/MainModal/index.test.js
- ui/src/Components/SilenceModal/index.js
- ui/src/Components/SilenceModal/index.test.js
- ui/src/Components/TooltipWrapper/index.js
This uses React code splitting to only load modal content components if they are used - all modal components will be loaded the first time user open a modal, rather than on initial page load
> feat(ui): lazy load modals

- ui/src/Components/SilenceModal/SilenceForm.js
- ui/src/Components/SilenceModal/SilenceForm.test.js
Alertmanager doesn't restrict this field, so no need to force an email there.
Fixes #741
> fix(ui): allow any string as silence author, not just email

- ui/src/Components/Labels/BaseLabel/index.scss
Bootstrap classes for.btn are getting priorioty so the text is always black, even when background color is dark
> fix(ui): apply correct font color to filter input labels

- ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/DeleteSilence.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/DeleteSilence.test.js
Makes it obvious that the UI didn't freeze on slow connections
> feat(ui): show a spinner while silence is being deleted

- internal/config/config.go
Timeout attribute for each alertmanager upstream should default to the value of alertmanager.timeout flag.
Without that it will default to 0s which will cause it to timeout instantly
> fix(backend): ensure that we always use default timeout for am requests

- ui/src/Components/Labels/LabelWithPercent/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/LabelWithPercent/index.js
- ui/src/Components/Labels/LabelWithPercent/index.test.js
- ui/src/Components/OverviewModal/OverviewModalContent.js
- ui/src/Components/OverviewModal/__snapshots__/OverviewModalContent.test.js.snap
A little nicer and cleaner view of the percent bar below labels
> feat(ui): add an offset to overview modal labels

- demo/karma.yaml
- docs/CONFIGURATION.md
- internal/config/config.go
- internal/config/config_test.go
- internal/config/models.go
- internal/models/api.go
- ui/src/Components/SilenceModal/SilenceForm.js
- ui/src/Components/SilenceModal/SilenceForm.test.js
- ui/src/Stores/AlertStore.js
- views.go
- views_test.go
>  feat: allow extracting silence author from auth headers

- ui/src/Components/OverviewModal/OverviewModalContent.js
- ui/src/Components/OverviewModal/OverviewModalContent.test.js
- ui/src/Components/OverviewModal/__snapshots__/OverviewModalContent.test.js.snap
We only render top 9 labels, add a counter showing how many were skipped
> feat(ui): show the number of hidden label on the overview modal

- ui/src/Components/Labels/LabelWithPercent/__snapshots__/index.test.js.snap
- ui/src/Components/Labels/LabelWithPercent/index.js
- ui/src/Components/OverviewModal/__snapshots__/OverviewModalContent.test.js.snap
These get triggered too often, blocking view of other labels
> chore(ui): disable tooltips on the overview modal

- ui/src/Components/SilenceModal/AlertManagerInput/index.js
- ui/src/Components/SilenceModal/AlertManagerInput/index.test.js
Removing last value sets the value that's expected to be a list to null, which breaks some logic, ensure we always have a list there.
Fixes #826
> fix(ui): don't crash when removing last Alertmanager instance

- ui/src/Components/SilenceModal/SilenceMatch/LabelValueInput.js
- ui/src/Components/SilenceModal/SilenceMatch/LabelValueInput.test.js
Removing last value sets the value that's expected to be a list to null, which breaks some logic, ensure we always have a list there
Fixes #827
> fix(ui): don't crash when removing last matcher value

- ui/src/Components/NavBar/FilterInput/index.js
- ui/src/Components/NavBar/FilterInput/index.test.js
Focusing input on a mobile browser pulls in the keyboard view, which takes half of the screen. Let user click it manually if needed
> chore(ui): don't focus input on mobile

- ui/package-lock.json
- ui/package.json
- ui/src/Components/Grid/AlertGrid/AlertGroup/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.js
This is to avoid rendering lots of expensive components while they're not in the viewport.
Should provide some performance improvements when there's plenty of alerts.
> feat(ui): lazy render alert group content

- .commitlintrc.js
Lots of renovate PRs include commits with long subjects since they include dependency name.
Fixing it always requires either ignoring failed CI jobs or manually editing the subject.
Better to allow long subjects
> chore(ci): bump header-max-length to 100

- ui/package-lock.json
- ui/package.json
- ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/DeleteSilence.js
- ui/src/Components/MainModal/index.js
- ui/src/Components/Modal/index.js
- ui/src/Components/Modal/index.test.js
- ui/src/Components/OverviewModal/index.js
- ui/src/Components/SilenceModal/index.js
> feat(ui): close modal window when user hits the Escape key

- ui/src/Components/Modal/index.js
HotKeys component needs to be unmounted on hide, otherwise we might have multiple modals responding to key events
> fix(ui): disable hotkeys when modal is hidden

- ui/src/App.scss
- ui/src/Components/Labels/BaseLabel/index.scss
- ui/src/Components/Labels/FilterInputLabel/index.scss
- ui/src/Components/Labels/LabelWithPercent/index.scss
- ui/src/Components/MainModal/Configuration/InputRange.scss
- ui/src/Components/NavBar/index.scss
- ui/src/Components/OverviewModal/index.scss
- ui/src/Components/SilenceModal/DateTimeSelect/index.scss
- ui/src/Fonts.scss
- ui/src/empty.css
All scss imports needs to use App.scss, otherwise some overrides won't be present, like font swap Lato -> Open Sans
> fix(ui): cleanup scss variable imports

- go.mod
- go.sum
This fixes some cardinality issues with exported metrics
https://github.com/zsais/go-gin-prometheus/pull/35
> chore(backend): upgrade go-gin-prometheus to the latest version

- .travis.yml
Right now CI jobs that build all binaries and/or docker images run twice - for branch job and PR job.
Those jobs are slow so skip PR jobs, one is enough.
> chore(ci): run build CI jobs only from master branch

- .travis.yml
This way we don't create a dedicated cache file
> fix(ci): move time zone test env variable to script

- Dockerfile
- Makefile
- demo/Dockerfile
Copy only what's needed rather then entire repo, needs more steps but allows for faster builds
> fix(build): speed up docker builds

- ui/src/Components/OverviewModal/OverviewModalContent.js
- ui/src/Components/OverviewModal/__snapshots__/OverviewModalContent.test.js.snap
Moves the left column labels to the top, since the right side will have progress bars
at the bottom which makes them taller
> fix(ui): align labels in the overview modal

- internal/alertmanager/models.go
> chore(backend): log a warning when alertmanager 0.17 or 0.18 is detected

- ui/src/Components/Fetcher/index.js
- ui/src/Components/Fetcher/index.test.js
- ui/src/Stores/AlertStore.js
Right now fetcher will always trigger fetch if enough time passes, make it aware of the last fetch timestamp so the timer resets after each fetch
> chore(ui): only fetch updates if  seconds passed since last fetch

- ui/src/Common/Fetch.js
- ui/src/Common/Fetch.test.js
- ui/src/Components/AlertAck/index.js
- ui/src/Components/MainModal/Configuration/SortLabelName.js
- ui/src/Components/ManagedSilence/DeleteSilence.js
- ui/src/Components/NavBar/FilterInput/index.js
- ui/src/Components/SilenceModal/Browser/index.js
- ui/src/Components/SilenceModal/SilenceMatch/LabelNameInput.js
- ui/src/Components/SilenceModal/SilenceMatch/MatchCounter.js
- ui/src/Components/SilenceModal/SilencePreview/index.js
- ui/src/Components/SilenceModal/SilencePreview/index.test.js
- ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitProgress.js
- ui/src/Stores/AlertStore.js
This should play better with auth middlewares that uses redirects since CORS will no longer break the redirect chain
> fix(ui): use mode:no-cors for fetch GET requests

- ui/src/App.scss
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.scss
- ui/src/Components/Labels/BaseLabel/index.scss
- ui/src/Components/Labels/FilterInputLabel/index.scss
- ui/src/Components/Labels/LabelWithPercent/index.scss
- ui/src/Components/MainModal/Configuration/InputRange.scss
- ui/src/Components/ManagedSilence/index.scss
- ui/src/Components/Modal/index.scss
- ui/src/Components/NavBar/index.scss
- ui/src/Components/OverviewModal/index.scss
- ui/src/Components/SilenceModal/DateTimeSelect/index.scss
- ui/src/DarkTheme.scss
- ui/src/Theme.scss
bootstrap css gets injected multiple time due to how imports are structured, only import variables in component scss
> fix(ui): avoid duplicating bootstrap styles

- cmd/karma/metrics.go
If there are no alerts for given state we won't return any metric, which leads to gaps
on metrics. Fix it by initializing all states with 0.
> fix(backend): always zero exposed alert count metrics

- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/__snapshots__/index.test.js.snap
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap
- ui/src/Components/ManagedSilence/__snapshots__/index.test.js.snap
- ui/src/Styles/Components/AlertGroup.scss
- ui/src/Styles/Components/BaseLabel.scss
Right now margin is set after each element rather than to enfore space between two elements
> fix(ui): margin should only be set between elements

- ui/src/App.tsx
- ui/src/Styles/App.scss
- ui/src/Styles/FontBundle.scss
- ui/src/Styles/Fonts.scss
This ensures that the grid renders correctly, since load events don't seem to trigger on storybook and grid is not repacked after element heights changes.
> fix(ci): don't try to load fonts on Percy

- .travis.yml
If we run over 5k snapshots a month we'll get failures, so it should
be allowed to fail
> fix(ci): allow percy tests to fail

- renovate.json
This prevents renovate from bumping LTS version.
> fix(project): disable automerge for node major versions

- cmd/karma/main.go
- cmd/karma/proxy.go
- cmd/karma/proxy_test.go
- internal/mapper/mapper.go
- internal/mapper/v017/api.go
- internal/mapper/v017/silences.go
When authentication is enabled and proxy mode is on then ensure all silences are created with the username from credentials, rather than what the user sends.
> feat(backend): use username from credentials for silences

- .travis.yml
- Makefile
Travis cache gets corrupted from time to time, try to work around that by nuking node_modules when npm install fails
> fix(ci): nuke node_modules on failed install

- Makefile
Move node_modules wipe to run on build failure and only in CI
> fix(ci): nuke node_modules on failed build

- ui/src/Components/Grid/AlertGrid/Grid.js
If we have multi-grid on, user toggles all grids to hide details, then disables multi-grid, then we end up with alerts hidden and no way to show them.
> fix(ui): always render alerts if multi-grid is disabled

- demo/karma.yaml
severity is already used for multi-grid, so second level sorting should use something else
> fix(demo): sort alerts by cluster label

- ui/Makefile
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.test.js
- ui/src/Components/NavBar/FilterInput/History.test.js
This fails tests when there are unhandled promise rejections when running tests
> fix(tests): pass --unhandled-rejections=strict to nodejs

- ui/package-lock.json
- ui/package.json
atom-prettier doesn't work with the latest version, keep it on 2.0.2 until it's fixed
> fix(deps): downgrade prettier to 2.0.2

- cmd/karma/tests/testscript/duplicated_alertmanager_default_name.txt
- cmd/karma/tests/testscript/empty_alertmanager_name.txt
- internal/config/config.go
> fix(backend): ensure alertmanager server uses default name if not set

- ui/package-lock.json
- ui/package.json
This reverts commit 90c4bc856e4109a2cee217497a3b774f9000ae1f.
Fails to load, waiting for a fix upstream.
> fix(deps): revert update dependency moment to v2.25.0

- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
- ui/src/Styles/Components/Alert.scss
This makes buttons less likely to have a unique width. Alert labels will be better aligned.
> fix(ui): set min-width on alert menu button

- ui/src/Hooks/useFetchGet.js
- ui/src/Hooks/useFetchGet.test.js
Don't try to set the response if request was canceled
> fix(ui): fix cleanup in useFetchGet hook

- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.js
- ui/src/Components/InlineEdit/index.js
- ui/src/Components/NavBar/FilterInput/History.js
- ui/src/Components/TooltipWrapper/index.js
- ui/src/Hooks/useOnClickOutside.js
- ui/src/Hooks/useOnClickOutside.test.js
useOnClickOutside should start listening for events only if there's an action to take.
Fixes #1754
> fix(ui): only trigger useOnClickOutside when needed

- ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.test.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.js
- ui/src/Components/Grid/AlertGrid/Grid.js
- ui/src/Components/Grid/AlertGrid/index.test.js
- ui/src/Hooks/useGrid.js
- ui/src/Hooks/useGrid.test.js
afterUpdate callback is chaning on every render, triggering annotation re-render
> fix(ui): avoid annotation re-renders

- ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
When default alert render count is changed all groups should reflect it
> fix(ui): always use defaults for alert render count

- ui/src/Components/AlertAck/index.js
- ui/src/Components/AlertAck/index.test.js
If acking an alert fails we render failure icon, but there's no way to try again. Reset button after 20s.
> fix(ui): reset failed ack button after 20s

- ui/src/Components/Modal/index.js
Modal will hide the scrollbar, which can resize everything.
Tell body-scroll-lock to reserver space for hidden scrollbar to avoid it.
> fix(ui): don't resize the grid when modal is open

- make/go.mk
Make sure the just-built assetfs binary is used.
> fix(make): use GOBIN in all assetfs invocations

- ui/src/Components/FaviconBadge/index.tsx
Some browsers (like Firefox, on both high and low DPI monitors, and Google Chrome beta on low DPI monitors) render the favico.js badge too thin.
This is how it looks in Firefox without and with this patch:
Fixes: #2107
> fix(ui): improve favicon readability on Firefox

- ui/src/setupTests.ts
New mobx doesn't need it anymore
> fix(ui): remove obsolete imports

- cmd/karma/metrics.go
If last api call failed, the metric is 0, otherwise 1.
This makes writing alerting rules clearer, rather than `rate(karma_alertmanager_errors_total[5m])` or similar.
> feat(backend): add metric alertmanager_up

- cmd/karma/exporter.go
Default buckets cover up to 10 seconds, which is unnecessarily wide.
Checking our installation, highest p99.9 among all endpoints is 0.34s (somewhat unexpectedly, the notFound handler).
> feat(backend): use fewer histogram buckets for request latency

- .travis.yml
This PR adds a push to the "new" [Github Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry) (I kept the push to the "old" Github Package Registry since I guess people may have workflow dependencies on it?).
The new registry has two benefits:
- Allows for unauthenticated pulls (ie no longer need to authenticate your AM nodes with GitHub to get the image)
- Isn't affected by the [bug which appears to break containerd](https://github.com/containerd/containerd/issues/3291)
> Push to new GitHub Container Registry

- cmd/karma/tests/testscript/059_log_full_config_env.txt
- internal/config/config.go
SILENCEFORM_AUTHOR_POPULATE_FROM_HEADER_* env support was removed, but old code is still present, remove it.
Correctly parse AUTHENTICATION_HEADER_VALUE_RE env variable into authentication.header.value_re config option.
Fixes #2246
> fix(backend): correctly handle AUTHENTICATION_HEADER_VALUE_RE env variable

- renovate.json
- Replace `masterIssue` with `dependencyDashboard`
Renovate bot has deprecated the use of `masterIssue`, and now uses `dependencyDashboard` instead.
The functionality of the dashboard does not change when you merge this PR, so you'll keep your dependencyDashboard. 😉 
The Renovate docs for `dependencyDashboard` can be found here: https://docs.renovatebot.com/configuration-options/#dependencydashboard
The Renovate bot _should_ have raised a PR to migrate you to the newer term (https://github.com/renovatebot/renovate/pull/6729), but I cannot find a PR like that in the PR list for your repository.
Maybe you hit some kind of bug in this repository that causes the bot to not update you via a PR.
At least now you're using the latest supported term. 👍
> chore: masterIssue -> dependencyDashboard

- CHANGELOG.md
- cmd/karma/api_test.go
- internal/alertmanager/dedup.go
> fix(backend): strip labels from alert group when configured

- CHANGELOG.md
- cmd/karma/main_test.go
- cmd/karma/timer.go
- cmd/karma/views_test.go
- internal/alertmanager/models.go
ClusterMemberNames can aquire read lock twice, which could block write locks.
Fixes #2888
> fix(backend): fix a deadlock in ClusterMemberNames()

- cmd/karma/main.go
- cmd/karma/views.go
- cmd/karma/views_test.go
If listen.prefix is set to /foo we should redirect /foo => /foo/
Fixes 3084
> fix(backend): redirect to slash

- CHANGELOG.md
- cmd/karma/views.go
Fix error:
```
2021/07/23 15:19:54 http: panic serving 127.0.0.1:65037: assignment to entry in nil map
goroutine 654 [running]:
net/http.(*conn).serve.func1(0xc0002114a0)
/opt/hostedtoolcache/go/1.16.6/x64/src/net/http/server.go:1804 +0x153
panic(0xca4ae0, 0x16537f0)
/opt/hostedtoolcache/go/1.16.6/x64/src/runtime/panic.go:971 +0x499
github.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc0004a95f0, 0xc0006b97a0, 0xc0002f3e00)
/home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.11.0/http/sentryhttp.go:117 +0x14e
panic(0xca4ae0, 0x16537f0)
/opt/hostedtoolcache/go/1.16.6/x64/src/runtime/panic.go:965 +0x1b9
main.alerts(0x1670bd0, 0xc000bb1400, 0xc0002f3e00)
/home/runner/work/karma/karma/cmd/karma/views.go:427 +0x3454
net/http.HandlerFunc.ServeHTTP(0x15a0d48, 0x1670bd0, …
```
> Fix for an error in views.go

- cmd/karma/acl.go
Hi, found this while finally trying to use the new feature added in #3558. Group names coming from a proxy can't be properly validated like this.
> fix(acl): Do not validate group names from proxies

- CHANGELOG.md
- ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/index.tsx
- ui/src/Components/Grid/AlertGrid/AlertGroup/index.tsx
> fix(ui): only hide group footer if there's nothing to render
