.travis.yml

CI moved from travis-ci.org to travis-ci.com, it needs a new token

chore(ci): update api token for releases

---

.travis.yml
Makefile

No longer needed - https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0

chore(ci): drop greenkeeper-lockfile

---

ui/src/Components/NavBar/FilterInput/index.js
ui/src/Components/SilenceModal/LabelNameInput.js
ui/src/Stores/AlertStore.js

fix(ui): always pass credentials with fetch()

---

ui/src/Components/Fetcher/index.js
ui/src/Components/Fetcher/index.test.js

Refactor the timer so instead of calling fetch directly every  seconds we call it every 1 second, check if we could & should fetch (fetch isn't already/still in progress and  seconds passed since last fetch) and if needed call fetch.
This will also allow us to pause fetches when user is interacting with alerts so there's no whack-a-mole with buttons

refactor(ui): prevent concurrent fetches

---

ui/package-lock.json
ui/package.json

node-sass-chokidar is a wrapper around node-sass, use node-sass directly

chore(ui): replace node-sass-chokidar with node-sass

---

.travis.yml

Docs are clear that it's 'required' rather than true

fix(travis): use correct 'sudo' value

---

ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/index.test.js
ui/src/Components/MultiSelect/__snapshots__/index.test.js.snap
ui/src/Components/MultiSelect/index.js
ui/src/Components/MultiSelect/index.test.js
ui/src/Components/SilenceModal/AlertManagerInput.js
ui/src/Components/SilenceModal/AlertManagerInput.test.js
ui/src/Components/SilenceModal/SilenceForm.js
ui/src/Components/SilenceModal/SilenceForm.test.js
ui/src/Components/SilenceModal/SilenceModalContent.js
ui/src/Components/SilenceModal/SilenceModalContent.test.js
ui/src/Stores/SilenceFormStore.js
ui/src/Stores/SilenceFormStore.test.js
ui/src/Stores/__snapshots__/SilenceFormStore.test.js.snap
ui/src/__mocks__/Alerts.js

feat(ui): allow editing exiting silences

---

ui/package.json
ui/src/index.js
ui/yarn.lock

fix(ui): add polyfill for es2015+ features for older browsers

---

ui/package.json
ui/src/Components/NavBar/index.js
ui/src/index.js

This allows it to run on all browsers from the browserslist config

fix(ui): polyfill fetch()

---

Gopkg.lock
Gopkg.toml

React deps are pinned, so should be Go deps

chore(api): pin Go dependencies

---

proxy.go
proxy_test.go

fix(api): proxy when upstream url has a path

---

README.md

https://hub.docker.com/r/prymitive/karma/ doesn't exist. https://hub.docker.com/r/lmierzwa/karma/ appears to be the correct location

Update docker repository locations

---

assets.go
assets_test.go
demo/Dockerfile
demo/custom.js
demo/karma.yaml
docs/CONFIGURATION.md
docs/example.yaml
internal/config/config.go
internal/config/config_test.go
internal/config/models.go
main.go
ui/public/index.html

 feat(project): add support for loading extra css/js files

---

.golangci.yml
alerts.go
api_test.go
internal/alertmanager/models.go
internal/models/alertmanager.go
internal/slices/slices.go
internal/slices/slices_test.go
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.test.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/index.test.js
ui/src/Components/Grid/AlertGrid/index.js
ui/src/Components/Grid/AlertGrid/index.test.js
ui/src/Components/Grid/index.test.js
ui/src/Components/SilenceModal/AlertManagerInput/__snapshots__/index.test.js.snap
ui/src/Components/SilenceModal/AlertManagerInput/index.js
ui/src/Components/SilenceModal/AlertManagerInput/index.test.js
ui/src/Components/SilenceModal/Matchers.js
ui/src/Components/SilenceModal/SilenceMatch/MatchCounter.test.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitController.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitController.test.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitProgress.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitProgress.test.js
ui/src/Components/SilenceModal/SilenceSubmit/__snapshots__/SilenceSubmitProgress.test.js.snap
ui/src/Models/API.js
ui/src/Stores/AlertStore.js
ui/src/__mocks__/Alerts.js
views.go

fix(ui): improve support for HA clusters

---

go.sum

Running build locally adds those, push it to git

chore(build): add missing lines to go.sum

---

.travis.yml

Empty list doesn't work correctly, it still tries to cache

fix(ci): correctly disable cache on Travis CI

---

ui/src/Components/SilenceModal/SilenceMatch/index.js

This will use bootstrap styled controls instead of native.
https://getbootstrap.com/docs/4.2/components/forms/#switches

feat(ui): use bootstrap custom control for checkboxes

---

alerts.go
api_test.go
internal/models/api.go
ui/src/Stores/AlertStore.js
ui/src/__mocks__/Fetch.js
views.go
views_test.go

Not used by any UI code, remove it.

chore(api): drop counters from API response

---

docs/CONFIGURATION.md
internal/alertmanager/dedup.go
internal/config/config.go
internal/config/config_test.go
internal/config/models.go
internal/transform/strip.go
internal/transform/strip_test.go

This allows same filtering we already have with labels. Fixes #312

feat(backend): allow stripping annotations

---

.travis.yml

Docker Hub keep failing jobs and is quite slow, move deployment to Travis CI, that way everything is deployed from there.

feat(docker): build and deploy docker images from Travis CI

---

ui/src/Components/NavBar/FilterInput/Constants.js
ui/src/Components/NavBar/FilterInput/__snapshots__/index.test.js.snap
ui/src/Components/NavBar/FilterInput/index.css
ui/src/Components/NavBar/FilterInput/index.js

This is to make @tarnfeld happy

fix(ui): align autocomplete dropdown with the input

---

docs/CONFIGURATION.md
internal/alertmanager/tls.go
internal/config/config.go
internal/config/config_test.go
internal/config/models.go
main.go

feat(backend): allow disabling TLS certificate validation

---

renovate.json

Instead of 3 open PRs set a limit of 1 new PR per hour and enable nodejs updates in travis config

chore(renovate): tweak config

---

ui/package.json
ui/yarn.lock

2.4.0 doesn't work on mobile, revert to 2.3.0 until the issue is fixed upstream

fix(ui): revert react-select to 2.3.0

---

demo/karma.yaml
docs/CONFIGURATION.md
internal/config/config.go
internal/config/config_test.go
internal/config/models.go
internal/models/api.go
ui/src/Components/Grid/AlertGrid/index.js
ui/src/Components/Grid/AlertGrid/index.test.js
ui/src/Stores/AlertStore.js
ui/src/__mocks__/Fetch.js
views.go

This feature solves the problem of sorting by label when values have special meaning and alphabetic sort doesn't make sense for it.

feat(config): allow configuring label value mapping for sorting

---

ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.css
ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap
ui/src/Components/MultiSelect/__snapshots__/index.test.js.snap
ui/src/Components/MultiSelect/index.js
ui/src/Components/SilenceModal/AlertManagerInput/__snapshots__/index.test.js.snap

Using bootstrap means that we don't need to worry about browser compatibility, which in this case means Edge where this wasn't enough

refactor(ui): use bootstrap utilities for word breaks

---

ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/DeleteSilence.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitProgress.js

fix(ui): pass credentials when sending silences to alertmanager

---

README.md

fix(docs): add a note about supported Alertmanager releases

---

renovate.json

This is to test if it helps with renovatebot/renovate#3297

fix(renovate): enable masterIssue option

---

internal/config/config.go

This is a workaround until this issue is fixed upstream.
Fixes #507

fix(backend): workaround viper map key parsing

---

.github/stale.yml

This bot will handle closing old PRs that had no activity

chore(github): enable probot/stale bot

---

.travis.yml

Use fewer groups and avoid double building docker images on tag builds

chore(ci): speed up travis jobs

---

demo/generator.py
demo/karma.yaml
docs/CONFIGURATION.md
internal/transform/color_test.go
internal/transform/colors.go

feat(api): allow using wildcards with custom colors

---

ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/index.css
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.js

Cards only need color definition once, on the top level element

fix(ui): correctly set card background color

---

internal/alertmanager/dedup_test.go
internal/mock/0.17.0/api/v1/status
internal/mock/0.17.0/api/v2/alerts/groups
internal/mock/0.17.0/api/v2/silences
internal/mock/0.17.0/metrics
internal/mock/Makefile
internal/mock/mock.go
views_test.go

file:// scheme is not supported so we need some changes to always use mocks

feat(backend): add alertmanager v0.17.0 mock files for testing

---

ui/src/Components/MultiSelect/__snapshots__/index.test.js.snap
ui/src/Components/MultiSelect/index.js
ui/src/Components/SilenceModal/AlertManagerInput/__snapshots__/index.test.js.snap
ui/src/Components/SilenceModal/SilenceMatch/MatchCounter.js
ui/src/Components/SilenceModal/SilenceMatch/__snapshots__/LabelValueInput.test.js.snap
ui/src/Components/SilenceModal/SilenceMatch/__snapshots__/MatchCounter.test.js.snap

Counter badge is misaligned, fix it by setting line-height.
Close icon border padding is different than parent, ensure it's inherited to avoid mismatch

fix(ui): matcher badge and close icon css fixes

---

main.go

feat(backend): add --check-config flag for validating configuration

---

alerts.go
api_test.go
demo/generator.py
demo/karma.yaml
internal/models/api.go
internal/models/api_test.go
ui/src/Components/Labels/LabelWithPercent/__snapshots__/index.test.js.snap
ui/src/Components/Labels/LabelWithPercent/index.js
ui/src/Components/Labels/LabelWithPercent/index.scss
ui/src/Components/Labels/LabelWithPercent/index.test.js
ui/src/Components/MainModal/index.js
ui/src/Components/NavBar/index.css
ui/src/Components/NavBar/index.js
ui/src/Components/NavBar/index.scss
ui/src/Components/NavBar/index.test.js
ui/src/Components/OverviewModal/OverviewModalContent.js
ui/src/Components/OverviewModal/OverviewModalContent.test.js
ui/src/Components/OverviewModal/__snapshots__/OverviewModalContent.test.js.snap
ui/src/Components/OverviewModal/index.js
ui/src/Components/OverviewModal/index.scss
ui/src/Components/OverviewModal/index.test.js
ui/src/Components/SilenceModal/index.js
ui/src/Stores/AlertStore.js
ui/src/__mocks__/Fetch.js
views.go
views_test.go

feat(ui): add a modal with labels overview

---

docs/CONFIGURATION.md
internal/alertmanager/model_test.go
internal/alertmanager/models.go
internal/alertmanager/upstream.go
internal/config/config.go
internal/config/config_test.go
internal/config/models.go
main.go

feat(backend): add external_uri config option for alertmanager upstreams

---

.travis.yml
Makefile
go.mod
go.sum
tools.go

 fix(ci): build all possible platforms

---

.travis.yml

This avoids duplicating cache files, since all env variables are used to calculate the cache key

fix(ci): use name key for naming CI jobs

---

ui/src/Components/Grid/UpgradeNeeded/__snapshots__/index.test.js.snap
ui/src/Components/Grid/UpgradeNeeded/index.js

It's more noisy with the background

fix(ui): revert style changes for upgrade screen

---

ui/src/Components/Grid/UpgradeNeeded/index.js
ui/src/Components/Grid/UpgradeNeeded/index.test.js
ui/src/Components/Grid/index.js
ui/src/Components/Grid/index.stories.js

chore(ui): pass upgrade screen reload timer as props

---

ui/src/Components/Grid/AlertGrid/index.js
ui/src/Components/Grid/AlertGrid/index.test.js

fix(ui): prevent grid resize loops

---

ui/src/Components/Grid/AlertGrid/GridSize.js
ui/src/Components/Grid/AlertGrid/index.js
ui/src/Components/Grid/AlertGrid/index.test.js
ui/src/Components/Grid/index.stories.js

fix(ui): better handling of window resize events

---

ui/src/Components/Grid/EmptyGrid/__snapshots__/index.test.js.snap
ui/src/Components/Grid/EmptyGrid/index.js
ui/src/Components/Grid/EmptyGrid/index.scss
ui/src/Components/Grid/EmptyGrid/index.test.js
ui/src/Components/Grid/index.js
ui/src/Components/Grid/index.test.js

Makes it clear that there are no alerts, especially with hidden navbar

feat(ui): show an icon when the grid is empty

---

.travis.yml

This will save some snapshots since only tested changes will run

chore(ci): move percy tests to run after linters

---

.travis.yml

Overwriting versions is not supported

fix(ci): don't push :latest docker image to GitHub

---

cmd/karma/alerts.go
docs/CONFIGURATION.md
internal/alertmanager/model_test.go
internal/alertmanager/models.go
internal/alertmanager/upstream.go
internal/models/alertmanager.go
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/DeleteSilence.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/DeleteSilence.test.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Silence/index.test.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitProgress.js
ui/src/Components/SilenceModal/SilenceSubmit/SilenceSubmitProgress.test.js

fix(project): refactor proxy & external_uri handling

---

.travis.yml
Dockerfile
Makefile
demo/Dockerfile
internal/mapper/v017/Dockerfile

This ensures that we fail CI if the openapi client code that's commited to git is different than what the current code would generate

feat(ci): rebuild openapi client code in CI and check for differences

---

.travis.yml

https://blog.travis-ci.com/2019-10-24-build-config-validation

feat(ci): enable Travis config validation

---

.travis.yml

seems to be affecting releases

fix(ci): disable travis config validation

---

tools.go

Fix: Documentation Improvement

---

README.md
cmd/karma/main.go
cmd/karma/views.go
cmd/karma/views_test.go

feat(backend): add /health endpoint for healthcheck probes

---

ui/src/Common/Fetch.js
ui/src/Common/Fetch.test.js
ui/src/Components/SilenceModal/SilencePreview/index.test.js

responses for mode:no-cors requests have no body, which we need

fix(ui): revert use mode:no-cors for fetch GET requests

---

ui/package-lock.json

Fixes https://npmjs.com/advisories/1316

chore(ui): upgrade all 3rd party dependencies

---

.travis.yml
Makefile
ui/package-lock.json
ui/package.json

This reverts commit b0e74b907f49937b1e37c6e294a6176bcf653cf7.
Too many failure in CI when talking to the npm registry.

revert(ci): revert verify used js licenses in CI

---

ui/package-lock.json
ui/package.json
ui/src/Stores/AlertStore.js
ui/src/Stores/AlertStore.test.js

Try a few times before showing errors to users

feat(ui): retry failed alert fetch() calls

---

ui/.storybook/presets.js
ui/package-lock.json
ui/package.json

Storybook support for Create React App is now a separate preset.
The built-in preset will be disabled in Storybook 6.0.

chore(storybook): migrate to @storybook/preset-create-react-app

---

ui/public/index.html

fix(ui): add use-credentials to the manifest link

---

cmd/karma/main.go
internal/alertmanager/upstream.go

fix(backend): mask credentials in error logs

---

renovate.json

Previous commit doesn't work properly.

fix(project): move all automerge options to package rules

---

cmd/karma/views_test.go
internal/config/config.go
internal/config/config_test.go

fix(backend): empty string slice configuration options end up being nil

---

ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.js
ui/src/Components/Grid/AlertGrid/index.test.js

feat(ui): toggle all groups on alt+click

---

ui/src/Components/SilenceModal/DateTimeSelect/Duration.js
ui/src/Components/SilenceModal/DateTimeSelect/HourMinute.js
ui/src/Components/SilenceModal/DateTimeSelect/__snapshots__/index.test.js.snap
ui/src/Components/SilenceModal/DateTimeSelect/index.test.js

feat(ui): update silence form duration on mouse wheel

---

ui/src/Components/Labels/StaticLabel/index.js
ui/src/Components/ManagedSilence/DeleteSilence.js
ui/src/Components/ManagedSilence/DeleteSilence.test.js
ui/src/Components/SilenceModal/SilencePreview/index.js
ui/src/Components/SilenceModal/SilencePreview/index.test.js

Previews got broken due to API changes needed for multi-grid, this fixes it.
Fixes #1573

fix(ui): fix regression in silence preview

---

Makefile
go.mod
go.sum
tools.go

This one contains fixes for some issues like out of bound panics.

fix(tests): use gocovmerge fork

---

ui/src/Stores/SilenceFormStore.js
ui/src/Stores/SilenceFormStore.test.js

fix(ui): only use shared labels for group silences

---

ui/package-lock.json
ui/package.json

mobx-react-lite is used by mobx-react, add it to deps to get updates via dependabot

fix(ui): add mobx-react-lite to deps

---

internal/models/annotation.go
internal/models/annotation_test.go

fix(ui): correctly handle annotations with spaces after the link

---

ui/src/Components/Pagination/index.js
ui/src/Components/Pagination/index.test.js

This often overflows on mobile, render only 3 page links there

fix(ui): render smaller pagination range on mobile

---

ui/package-lock.json
ui/package.json

This reverts commit b4cb68d883b61fc538dcd4a413cf28eb533fdc64.

fix(deps): revert update dependency moment to v2.25.1

---

ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
ui/src/Styles/Components/Alert.scss

This reverts commit c4f4f6cff816ecb5bf3416bb2ffa28f5419242ba.

fix(ui): revert set min-width on alert menu button

---

ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/Annotation/index.js
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.js.snap

fix(ui): collapse annotations when clicking on the name

---

ui/package.json
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.test.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.js.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.js
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.test.js
ui/src/Components/NavBar/FilterInput/History.js
ui/src/Components/NavBar/index.stories.js
ui/src/__mocks__/react-onclickoutside.js

fix(ui): drop react-onclickoutside

---

ui/src/Components/SilenceModal/SilenceForm.js
ui/src/Components/SilenceModal/SilenceForm.test.js

fix(ui): add regex filters to default silence matchers

---

cmd/karma/views.go
cmd/karma/views_test.go

fix(backend): ensure we always close zsrd reader

---

ui/src/Components/FaviconBadge/index.js
ui/src/Components/FaviconBadge/index.test.js

fix(ui): favicon counter should render on first mount

---

ui/.storybook/config.js
ui/.storybook/main.js
ui/.storybook/presets.js
ui/package-lock.json
ui/package.json

This reverts commit 38cd75b439b3a6fbd8c7a1eda4e0391ff3faa821.

chore(storybook): remove storybook-addon-performance addon

---

ui/src/Components/Labels/FilterInputLabel/index.js

fix(ui): resume updates before editing filters

---

ui/src/App.test.js
ui/src/App.tsx
ui/src/AppBoot.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.js
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/AlertMenu.test.js
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.js
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.test.js
ui/src/Components/SilenceModal/AlertManagerInput/index.js
ui/src/Components/SilenceModal/SilenceForm.js
ui/src/Components/SilenceModal/SilenceForm.test.js
ui/src/Components/SilenceModal/SilenceMatch/index.js
ui/src/Components/SilenceModal/SilenceModalContent.js
ui/src/Components/SilenceModal/index.test.js
ui/src/Stores/SilenceFormStore.js
ui/src/Stores/SilenceFormStore.test.js

feat(ui): allow sharing pre-filled silence form via a link

---

cmd/karma/main.go

fix(backend): don't anchor linkDetect rule regexes

---

ui/package-lock.json

Resolve npm audit failure due to yargs prototype pollution.
See https://npmjs.com/advisories/1500 for more information.

fix: update yargs for https://npmjs.com/advisories/1500

---

ui/src/Components/Grid/UpgradeNeeded/index.tsx

fix(ui): csshake scss generates unique css on every build

---

cmd/karma/proxy.go
cmd/karma/proxy_test.go

fix(backend): set per alertmanager headers in proxy requests

---

ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.tsx.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/GroupMenu.tsx
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupHeader/index.tsx
ui/src/Components/Grid/AlertGrid/AlertGroup/__snapshots__/Silences.test.tsx.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/index.tsx
ui/src/Components/Grid/AlertGrid/Swimlane.tsx
ui/src/Components/ManagedSilence/SilenceComment.tsx
ui/src/Components/ManagedSilence/__snapshots__/SilenceComment.test.tsx.snap
ui/src/Components/ManagedSilence/__snapshots__/index.test.tsx.snap
ui/src/Components/OverviewModal/OverviewModalContent.test.tsx
ui/src/Components/OverviewModal/OverviewModalContent.tsx
ui/src/Components/SilenceModal/DateTimeSelect/Duration.tsx
ui/src/Components/SilenceModal/DateTimeSelect/HourMinute.tsx
ui/src/Components/SilenceModal/DateTimeSelect/__snapshots__/index.test.tsx.snap
ui/src/Components/SilenceModal/SilenceForm.test.tsx
ui/src/Components/SilenceModal/SilenceForm.tsx
ui/src/Styles/Components/WithClick.scss
ui/src/Styles/Components/_index.scss
ui/src/Styles/DarkTheme.scss
ui/src/Styles/LightTheme.scss

fix(ui): use bigger icons for alert group header

---

cmd/karma/alerts.go
go.mod
go.sum
internal/models/api.go

chore(deps): migrate to new sortorder import path

---

.github/workflows/test.yml

fix(ci): pass version when building docker images

---

.github/workflows/test.yml
.gitignore

fix(ci): don't prefix files with artifacts/ in sha512sum.txt

---

CHANGELOG.md
ui/src/Components/SilenceModal/SilenceMatch/LabelValueInput.test.tsx
ui/src/Components/SilenceModal/SilenceMatch/LabelValueInput.tsx

fix(ui): don't reset regex selection

---

CHANGELOG.md

fix(docs): update invalid changelog entry

---

cmd/karma/main_test.go
cmd/karma/timer.go
cmd/karma/views_test.go

fix(backend): enforce 5s sleep between upstream pulls

---

CHANGELOG.md
internal/alertmanager/models.go

fix(backend): avoid potential recursive locks

---

internal/alertmanager/models.go
internal/alertmanager/models_test.go

fix(api): use relative URIs for proxy endpoints

---

go.mod
go.sum
internal/transform/colors.go

Forked code doesn't require any locks

fix(backend): use randomcolor fork

---

CHANGELOG.md
cmd/karma/main.go
cmd/karma/views.go
internal/models/api.go
internal/models/api_test.go
ui/src/Components/Grid/AlertGrid/Grid.tsx
ui/src/Components/Grid/AlertGrid/Swimlane.tsx
ui/src/Components/Grid/AlertGrid/index.test.tsx
ui/src/Components/Grid/AlertGrid/index.tsx
ui/src/Components/NavBar/index.tsx
ui/src/Styles/Components/_AlertGrid.scss

feat(api): string grid labels from alert groups

---

CHANGELOG.md
cmd/karma/main.go
cmd/karma/views.go
cmd/karma/views_test.go

feat(api): add /version endpoint

---

ui/src/Components/MainModal/Help.tsx
ui/src/Components/MainModal/__snapshots__/Help.test.tsx.snap

help: add example to filter on non-existent label

---

CHANGELOG.md
internal/models/__snapshots__/models.snapshot
internal/models/api.go
internal/models/api_test.go

fix(api): correctly handle sub-uri sources in history

---

CHANGELOG.md
ui/src/Stores/SilenceFormStore.test.ts
ui/src/Stores/SilenceFormStore.ts

fix(ui): merge labels before generating silence matchers

---

CHANGELOG.md
cmd/karma/alert_history.go
cmd/karma/alert_history_test.go
cmd/karma/tests/testscript/060_log_full_config_file.txt
cmd/karma/tests/testscript/103_alert_history_tls.txt
cmd/karma/tests/testscript/104_alert_history_tls_bad.txt
cmd/karma/tests/testscript/105_alert_history_invalid_workers.txt
docs/CONFIGURATION.md
internal/config/config.go
internal/config/models.go

feat(backend): add tls options for history requests

---

CHANGELOG.md
docs/CONFIGURATION.md
ui/src/Components/AlertAck/index.test.tsx
ui/src/Components/AlertAck/index.tsx

feat(ui): allow acks to use local timezone

---

CHANGELOG.md
cmd/karma/alerts.go
cmd/karma/main.go
cmd/karma/tests/testscript/058_log_format_json.txt
cmd/karma/tests/testscript/062_log_timestamp.txt
cmd/karma/tests/testscript/064_log_timestamp_json.txt
cmd/karma/tests/testscript/064_no_args.txt
ui/src/Components/Grid/NoUpstream/__snapshots__/index.test.tsx.snap
ui/src/Components/Grid/NoUpstream/index.test.tsx
ui/src/Components/Grid/NoUpstream/index.tsx
ui/src/Components/Grid/index.test.tsx
ui/src/Components/Grid/index.tsx
ui/src/Components/Modal/index.test.tsx
ui/src/Components/NavBar/index.stories.tsx
ui/src/Components/NavBar/index.test.tsx
ui/src/Components/NavBar/index.tsx

fix(backend): log messages correctly with json and timestamps

---

ui/src/Components/SilenceModal/Browser/index.tsx

Animations make it less readable, disable transitions.

chore(ui): disable transitions on silence browser

---

CHANGELOG.md
demo/generator.py
ui/src/Common/Select.ts
ui/src/Components/Grid/AlertGrid/GridLabelSelect.tsx
ui/src/Components/MainModal/Configuration/AlertGroupCollapseConfiguration.tsx
ui/src/Components/MainModal/Configuration/AlertGroupSortConfiguration.tsx
ui/src/Components/MainModal/Configuration/GridLabelName.tsx
ui/src/Components/MainModal/Configuration/ThemeConfiguration.tsx
ui/src/Components/SilenceModal/Matchers.ts
ui/src/Components/SilenceModal/SilenceForm.test.tsx
ui/src/Components/SilenceModal/SilenceMatch/LabelValueInput.test.tsx
ui/src/Components/SilenceModal/SilenceMatch/LabelValueInput.tsx
ui/src/Components/SilenceModal/SilenceMatch/MatchCounter.test.tsx
ui/src/Stores/Settings.ts
ui/src/Stores/SilenceFormStore.test.ts
ui/src/Stores/SilenceFormStore.ts
ui/src/Stores/__snapshots__/SilenceFormStore.test.ts.snap
ui/src/__fixtures__/useFetchGet.ts

fix(ui): escape label values in silence form

---

cmd/karma/views.go

fix(backend): correctly count alerts in /silences.json

---

CHANGELOG.md
demo/generator.py
ui/src/Stores/SilenceFormStore.ts
ui/src/Stores/__snapshots__/SilenceFormStore.test.ts.snap

fix(ui): only escape regex values

---

CHANGELOG.md
ui/src/Hooks/useFetchAny.test.tsx
ui/src/Hooks/useFetchAny.ts
ui/src/Hooks/useFetchDelete.test.tsx
ui/src/Hooks/useFetchDelete.ts
ui/src/Hooks/useFetchGet.test.tsx
ui/src/Hooks/useFetchGet.ts

fix(ui): correctly handle 401 errors

---

CHANGELOG.md
ui/src/Components/SilenceModal/SilenceForm.test.tsx
ui/src/Components/SilenceModal/SilenceForm.tsx

fix(ui): fix regexp escape on auto-populated matchers

---

CHANGELOG.md
ui/src/Stores/SilenceFormStore.test.ts
ui/src/Stores/SilenceFormStore.ts

fix(ui): correctly unpack regexp matchers

---

CHANGELOG.md
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.test.tsx
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/index.tsx
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.tsx.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/index.test.tsx
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/index.tsx
ui/src/Components/Grid/AlertGrid/AlertGroup/index.test.tsx

fix(ui): don't render @cluster labels if there's only one

---

CHANGELOG.md
ui/src/Components/FaviconBadge/index.test.tsx
ui/src/Components/FaviconBadge/index.tsx

feat(ui): change badge if there's alertmanager error

---

docs/CONFIGURATION.md

fix(docs): fix a typo

---

CHANGELOG.md
ui/src/Components/Grid/AlertGrid/AlertGroup/Alert/__snapshots__/index.test.tsx.snap
ui/src/Components/Grid/AlertGrid/AlertGroup/GroupFooter/__snapshots__/index.test.tsx.snap
ui/src/Components/Labels/FilteringLabel/__snapshots__/index.test.tsx.snap
ui/src/Components/Labels/FilteringLabel/index.test.tsx
ui/src/Components/Labels/FilteringLabel/index.tsx
ui/src/Styles/Components/_BaseLabel.scss

feat(ui): copy label value on shift+click

---

CHANGELOG.md
ui/src/Components/Grid/index.test.tsx
ui/src/Components/Grid/index.tsx

fix(ui): always show alerts if there are any

---

CHANGELOG.md
cmd/karma/metrics.go
cmd/karma/tests/testscript/083_metrics.txt

feat(backend): add build_info metric

---

ui/src/Components/Labels/FilterInputLabel/index.tsx
ui/src/Components/Labels/FilteringCounterBadge/index.tsx
ui/src/Components/Labels/FilteringLabel/index.tsx
ui/src/Components/Labels/LabelWithPercent/index.tsx
ui/src/Stores/AlertStore.test.ts
ui/src/Stores/AlertStore.ts

Replace any existing opposing filter so you don't end up filtering away all alerts

feat: Replace opposing filter

---

CHANGELOG.md
ui/vite.config.ts

fix(ui): use relative paths for assets
